# Generated by Django 3.2.9 on 2022-03-13 04:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gt_admin', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='category_desc',
        ),
    ]
